name: CI

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 18.6.x
            prebuild: true

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Test
        run: |
          pnpm build:tsc
          pnpm test -- --no-color

      - name: Demo benchmarks
        run: |
          pnpm build:vite

          # - The demos are compiled to esm, so we enable ESM VM modules for jest
          export NODE_OPTIONS='--experimental-vm-modules'

          pnpm -F '@repris/jest-demo' bench:production

      - name: publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # NPM token config
          cat >.npmrc << 'EOF'
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          EOF

          # --no-git-checks because prepublish scripts may write files
          pnpm publish -r --access public --no-git-checks
